name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  injectable:
  logger:
  get_it:
  cupertino_icons: ^1.0.8
  auto_route: 8.3.0
  equatable: 2.0.5
  freezed_annotation: 2.4.4
  device_info_plus: ^10.1.2
  intl_phone_field:
  app_bloc:
    path: ../../app/app_bloc
  country_picker: ^2.0.27
  google_fonts: ^6.2.1
  rxdart:
  intl: ^0.18.1
  shimmer: ^3.0.0
  video_player: ^2.9.5
  lottie: ^3.2.0

dev_dependencies:
  auto_route_generator: 8.0.0
  injectable_generator: 2.6.2
  build_runner: 2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
